events = {
    "bloodbath": [
        {"tributes": 1, "killed": [], "string": "{p1} grabs a shovel."},
        {"tributes": 1, "killed": [], "string": "{p1} grabs a backpack and retreats."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} fight for a bag. {p1} gives up and retreats."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} fight for a bag. {p2} gives up and retreats."},
        {"tributes": 1, "killed": [], "string": "{p1} finds a bow, some arrows, and a quiver."},
        {"tributes": 1, "killed": [], "string": "{p1} runs into the cornucopia and hides."},
        {"tributes": 2, "killed": [], "string": "{p1} rips a mace out of {p2}'s hands."},
        {"tributes": 1, "killed": [], "string": "{p1} finds a canteen full of water."},
        {"tributes": 1, "killed": [], "string": "{p1} stays at the cornucopia for resources."},
        {"tributes": 1, "killed": [], "string": "{p1} gathers as much food as the can."},
        {"tributes": 1, "killed": [], "string": "{p1} grabs a sword."},
        {"tributes": 1, "killed": [], "string": "{p1} takes a spear from inside the cornucopia."},
        {"tributes": 1, "killed": [], "string": "{p1} finds a bag full of explosives."},
        {"tributes": 1, "killed": [], "string": "{p1} clutches a first aid kit and runs away."},
        {"tributes": 1, "killed": [], "string": "{p1} takes a sickle from inside the cornucopia."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} work together to get as many supplies as possible."},
        {"tributes": 1, "killed": [], "string": "{p1} runs away with a lighter and some rope."},
        {"tributes": 1, "killed": [], "string": "{p1} snatches a bottle of alcohol and a rag."},
        {"tributes": 1, "killed": [], "string": "{p1} finds a backpack full of camping equipment."},
        {"tributes": 1, "killed": [], "string": "{p1} grabs a backpack, not realizing it is empty."},
        {"tributes": 2, "killed": [], "string": "{p1} breaks {p2}'s nose for a basket of bread."},
        {"tributes": 4, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} share everything they gathered before running."},
        {"tributes": 1, "killed": [], "string": "{p1} retrieves a trident from inside the cornucopia."},
        {"tributes": 2, "killed": [], "string": "{p1} grabs a jar of fishing bait while {p2} gets fishing gear."},
        {"tributes": 2, "killed": [], "string": "{p1} scares {p2} away from the cornucopia."},
        {"tributes": 1, "killed": [], "string": "{p1} grabs a shield leaning on the cornucopia."},
        {"tributes": 1, "killed": [], "string": "{p1} snatches a pair of sais."},
        {"tributes": 1, "killed": [], "string": "{p1} steps off their podium too soon and blows up."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently steps on a landmine."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} catches {p2} off guard and kills them."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} work together to drown {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} after engaging in a fist fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots an arrow into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} cannot handle the circumstances and commits suicide."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head against a rock several times."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} snaps {p2}'s neck."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} decapitates {p2} with a sword."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} spears {p2} in the abdomen."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets {p2} on fire with a molotov."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a pit and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} while their back is turned."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2}, but puts them out of their misery."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2} and leaves them to die."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head in with a mace."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} pushes {p2} off a cliff during a knife fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s chest."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} is unable to convince {p2} to not kill them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} convinces {p2} to not kill them, only to kill {p2} instead."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a frozen lake and drowns."},
        {"tributes": 3, "killed": ["3"], "string": "{p1}, {p2}, and {p3} start fighting, but {p2} runs away as {p1} kills {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with their own weapon."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} overpowers {p2}, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets an explosive off, killing {p2}."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1} sets an explosive off, killing {p2}, and {p3}."},
        {"tributes": 4, "killed": ["2", "3", "4"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, and {p4}."},
        {"tributes": 5, "killed": ["2", "3", "4", "5"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, {p4} and {p5}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} as they tries to run."},
        {"tributes": 2, "killed": ["1", "2"], "string": "{p1} and {p2} threaten a double suicide. It fails and they die."},
        {"tributes": 4, "killed": ["1", "2", "3", "4"], "string": "{p1}, {p2}, {p3}, and {p4} form a suicide pact, killing themselves."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a hatchet."},
        {"tributes": 4, "killed": ["3", "4"], "string": "{p1} and {p2} fight {p3} and {p4}. {p1} and {p2} survive."},
        {"tributes": 4, "killed": ["1", "2"], "string": "{p1} and {p2} fight {p3} and {p4}. {p3} and {p4} survive."},
        {"tributes": 3, "killed": ["1"], "string": "{p1} attacks {p2}, but {p3} protects them, killing {p1}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely slices {p2} with a sword."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} with a rope."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} for their supplies."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} shoots an arrow at {p2}, but misses and kills {p3} instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots a poisonous blow dart into {p2}'s neck, slowly killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} with a tree branch."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} in the back with a trident."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p1} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p2} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "2"], "string": "{p1}, {p2}, and {p3} get into a fight. {p3} triumphantly kills them both."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} finds {p2} hiding in the cornucopia and kills them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} finds {p2} hiding in the cornucopia, but {p2} kills them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a sickle."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} and {p2} fight for a bag. {p1} strangles {p2} with the straps and runs."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} and {p2} fight for a bag. {p2} strangles {p1} with the straps and runs."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} repeatedly stabs {p2} to death with sais."}], 
    "day": [
        {"tributes": 1, "killed": [], "string": "{p1} goes hunting."},
        {"tributes": 1, "killed": [], "string": "{p1} injures themself."},
        {"tributes": 1, "killed": [], "string": "{p1} explores the arena."},
        {"tributes": 2, "killed": [], "string": "{p1} scares {p2} off."},
        {"tributes": 2, "killed": [], "string": "{p1} diverts {p2}'s attention and runs away."},
        {"tributes": 2, "killed": [], "string": "{p1} stalks {p2}."},
        {"tributes": 1, "killed": [], "string": "{p1} fishes."},
        {"tributes": 1, "killed": [], "string": "{p1} camouflauges themselves in the bushes."},
        {"tributes": 2, "killed": [], "string": "{p1} steals from {p2} while they aren't looking."},
        {"tributes": 1, "killed": [], "string": "{p1} makes a wooden spear."},
        {"tributes": 1, "killed": [], "string": "{p1} discovers a cave."},
        {"tributes": 2, "killed": [], "string": "{p1} attacks {p2}, but they manage to escape."},
        {"tributes": 2, "killed": [], "string": "{p1} chases {p2}."},
        {"tributes": 2, "killed": [], "string": "{p1} runs away from {p2}."},
        {"tributes": 1, "killed": [], "string": "{p1} collects fruit from a tree."},
        {"tributes": 1, "killed": [], "string": "{p1} receives a hatchet from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives clean water from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives medical supplies from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives fresh food from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} searches for a water source."},
        {"tributes": 2, "killed": [], "string": "{p1} defeats {p2} in a fight, but spares their life."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} work together for the day."},
        {"tributes": 2, "killed": [], "string": "{p1} begs for {p2} to kill them. They refuses, keeping {p1} alive."},
        {"tributes": 1, "killed": [], "string": "{p1} tries to sleep through the entire day."},
        {"tributes": 5, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} raid {p5}'s camp while they're hunting."},
        {"tributes": 1, "killed": [], "string": "{p1} constructs a shack."},
        {"tributes": 3, "killed": [], "string": "{p1} overhears {p2} and {p3} talking in the distance."},
        {"tributes": 1, "killed": [], "string": "{p1} practices their archery."},
        {"tributes": 1, "killed": [], "string": "{p1} thinks about home."},
        {"tributes": 1, "killed": [], "string": "{p1} is pricked by thorns while picking berries."},
        {"tributes": 1, "killed": [], "string": "{p1} tries to spear fish with a trident."},
        {"tributes": 1, "killed": [], "string": "{p1} searches for firewood."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} split up to search for resources."},
        {"tributes": 1, "killed": [], "string": "{p1} picks flowers."},
        {"tributes": 2, "killed": [], "string": "{p1} tends to {p2}'s wounds."},
        {"tributes": 1, "killed": [], "string": "{p1} sees smoke rising in the distance, but decides not to investigate."},
        {"tributes": 2, "killed": [], "string": "{p1} sprains their ankle while running away from {p2}."},
        {"tributes": 1, "killed": [], "string": "{p1} makes a slingshot."},
        {"tributes": 1, "killed": [], "string": "{p1} travels to higher ground."},
        {"tributes": 1, "killed": [], "string": "{p1} discovers a river."},
        {"tributes": 1, "killed": [], "string": "{p1} hunts for other tributes."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} hunt for other tributes."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} hunt for other tributes."},
        {"tributes": 4, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} hunt for other tributes."},
        {"tributes": 5, "killed": [], "string": "{p1}, {p2}, {p3}, {p4}, and {p5} hunt for other tributes."},
        {"tributes": 1, "killed": [], "string": "{p1} receives an explosive from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} questions their sanity."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} catches {p2} off guard and kills them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s head."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} begs for {p2} to kills them. They reluctantly oblige, killing {p1}."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} work together to drown {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} after engaging in a fist fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots an arrow into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} bleeds out due to untreated injuries."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} cannot handle the circumstances and commits suicide."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head against a rock several times."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} unknowingly eats toxic berries."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} silently snaps {p2}'s neck."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} taints {p2}'s food, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} decapitates {p2} with a sword."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from an infection."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} spears {p2} in the abdomen."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets {p2} on fire with a molotov."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a pit and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} while their back is turned."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2}, but puts them out of their misery."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2} and leaves them to die."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head in with a mace."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} attempts to climb a tree, but falls to their death."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} pushes {p2} off a cliff during a knife fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s chest."},
        {"tributes": 2, "killed": ["2"], "string": "{p1}'s trap kills {p2}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} while they are resting."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} is unable to convince {p2} to not kill them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} convinces {p2} to not kill them, only to kill them instead."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a frozen lake and drowns."},
        {"tributes": 3, "killed": ["3"], "string": "{p1}, {p2}, and {p3} start fighting, but {p2} runs away as {p1} kills {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with their own weapon."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} overpowers {p2}, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets an explosive off, killing {p2}."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1} sets an explosive off, killing {p2}, and {p3}."},
        {"tributes": 4, "killed": ["2", "3", "4"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, and {p4}."},
        {"tributes": 5, "killed": ["2", "3", "4", "5"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, {p4} and {p5}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} as they try to run."},
        {"tributes": 2, "killed": ["1", "2"], "string": "{p1} and {p2} threaten a double suicide. It fails and they die."},
        {"tributes": 4, "killed": ["1", "2", "3", "4"], "string": "{p1}, {p2}, {p3}, and {p4} form a suicide pact, killing themselves."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from hypothermia."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from hunger."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from thirst."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a hatchet."},
        {"tributes": 4, "killed": ["3", "4"], "string": "{p1} and {p2} fight {p3} and {p4}. {p1} and {p2} survive."},
        {"tributes": 4, "killed": ["1", "2"], "string": "{p1} and {p2} fight {p3} and {p4}. {p3} and {p4} survive."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies trying to escape the arena."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies of dysentery."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently detonates a land mine while trying to arm it."},
        {"tributes": 3, "killed": ["1"], "string": "{p1} attacks {p2}, but {p3} protects them, killing {p1}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} ambushes {p2} and kills them."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently steps on a landmine."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely slices {p2} with a sword."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} with a rope."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} for their supplies."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} shoots an arrow at {p2}, but misses and kills {p3} instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots a poisonous blow dart into {p2}'s neck, slowly killing them."},
        {"tributes": 6, "killed": ["4", "5", "6"], "string": "{p1}, {p2}, and {p3} successfully ambush and kill {p4}, {p5}, and {p6}."},
        {"tributes": 6, "killed": ["1", "2", "3"], "string": "{p1}, {p2}, and {p3} unsuccessfully ambush {p4}, {p5}, and {p6}, who kill them instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} with a tree branch."},
        {"tributes": 4, "killed": ["3"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They decides to kill {p3}."},
        {"tributes": 4, "killed": ["4"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They decides to kill {p4}."},
        {"tributes": 4, "killed": ["2"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They refuses to kill, so {p1} kills them instead."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} poisons {p2}'s drink, but mistakes it for their own and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} poisons {p2}'s drink. They drinks it and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} in the back with a trident."},
        {"tributes": 2, "killed": ["1", "2"], "string": "{p1} attempts to climb a tree, but falls on {p2}, killing them both."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p1} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p2} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "2"], "string": "{p1}, {p2}, and {p3} get into a fight. {p3} triumphantly kills them both."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a sickle."},
        {"tributes": 6, "killed": ["6"], "string": "{p1}, {p2}, {p3}, {p4}, and {p5} track down and kill {p6}."},
        {"tributes": 5, "killed": ["5"], "string": "{p1}, {p2}, {p3}, and {p4} track down and kill {p5}."},
        {"tributes": 4, "killed": ["4"], "string": "{p1}, {p2}, and {p3} track down and kill {p4}."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} track down and kill {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} tracks down and kills {p2}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} repeatedly stabs {p2} to death with sais."}], 
    "night": [
        {"tributes": 1, "killed": [], "string": "{p1} starts a fire."},
        {"tributes": 1, "killed": [], "string": "{p1} sets up camp for the night."},
        {"tributes": 1, "killed": [], "string": "{p1} loses sight of where they is."},
        {"tributes": 1, "killed": [], "string": "{p1} climbs a tree to rest."},
        {"tributes": 1, "killed": [], "string": "{p1} goes to sleep."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} tell stories about themselves to each other."},
        {"tributes": 4, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} sleep in shifts."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} sleep in shifts."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} sleep in shifts."},
        {"tributes": 1, "killed": [], "string": "{p1} tends to their wounds."},
        {"tributes": 1, "killed": [], "string": "{p1} sees a fire, but stays hidden."},
        {"tributes": 1, "killed": [], "string": "{p1} screams for help."},
        {"tributes": 1, "killed": [], "string": "{p1} stays awake all night."},
        {"tributes": 1, "killed": [], "string": "{p1} passes out from exhaustion."},
        {"tributes": 1, "killed": [], "string": "{p1} cooks their food before putting their fire out."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} run into each other and decide to truce for the night."},
        {"tributes": 4, "killed": [], "string": "{p1} fends {p2}, {p3}, and {p4} away from their fire."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} discuss the games and what might happen in the morning."},
        {"tributes": 1, "killed": [], "string": "{p1} cries themselves to sleep."},
        {"tributes": 1, "killed": [], "string": "{p1} tries to treat their infection."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} talk about the tributes still alive."},
        {"tributes": 1, "killed": [], "string": "{p1} is awoken by nightmares."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} huddle for warmth."},
        {"tributes": 1, "killed": [], "string": "{p1} thinks about winning."},
        {"tributes": 4, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} tell each other ghost stories to lighten the mood."},
        {"tributes": 1, "killed": [], "string": "{p1} looks at the night sky."},
        {"tributes": 2, "killed": [], "string": "{p1} defeats {p2} in a fight, but spares their life."},
        {"tributes": 2, "killed": [], "string": "{p1} begs for {p2} to kill them. They refuses, keeping {p1} alive."},
        {"tributes": 2, "killed": [], "string": "{p1} destroys {p2}'s supplies while they are asleep."},
        {"tributes": 5, "killed": [], "string": "{p1}, {p2}, {p3}, {p4}, and {p5} sleep in shifts."},
        {"tributes": 2, "killed": [], "string": "{p1} lets {p2} into their shelter."},
        {"tributes": 1, "killed": [], "string": "{p1} receives a hatchet from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives clean water from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives medical supplies from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} receives fresh food from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} tries to sing themselves to sleep."},
        {"tributes": 1, "killed": [], "string": "{p1} attempts to start a fire, but they are unsuccessful."},
        {"tributes": 1, "killed": [], "string": "{p1} thinks about home."},
        {"tributes": 2, "killed": [], "string": "{p1} tends to {p2}'s wounds."},
        {"tributes": 1, "killed": [], "string": "{p1} quietly hums."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} cheerfully sing songs together."},
        {"tributes": 1, "killed": [], "string": "{p1} is unable to start a fire and sleeps without warmth."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} hold hands."},
        {"tributes": 2, "killed": [], "string": "{p1} convinces {p2} to snuggle with them."},
        {"tributes": 1, "killed": [], "string": "{p1} receives an explosive from an unknown sponsor."},
        {"tributes": 1, "killed": [], "string": "{p1} questions their sanity."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} catches {p2} off guard and kills them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s head."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} begs for {p2} to kill them. They reluctantly obliges, killing {p1}."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} work together to drown {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} after engaging in a fist fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots an arrow into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} bleeds out due to untreated injuries."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} cannot handle the circumstances and commits suicide."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head against a rock several times."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} unknowingly eats toxic berries."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} silently snaps {p2}'s neck."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} taints {p2}'s food, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} decapitates {p2} with a sword."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from an infection."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} spears {p2} in the abdomen."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets {p2} on fire with a molotov."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a pit and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} while their back is turned."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2}, but puts them out of their misery."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2} and leaves them to die."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head in with a mace."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} attempts to climb a tree, but falls to their death."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} pushes {p2} off a cliff during a knife fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s chest."},
        {"tributes": 2, "killed": ["2"], "string": "{p1}'s trap kills {p2}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} while they are sleeping."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} is unable to convince {p2} to not kill them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} convinces {p2} to not kill them, only to kill {p2} instead."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a frozen lake and drowns."},
        {"tributes": 3, "killed": ["3"], "string": "{p1}, {p2}, and {p3} start fighting, but {p2} runs away as {p1} kills {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with their own weapon."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} overpowers {p2}, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets an explosive off, killing {p2}."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1} sets an explosive off, killing {p2}, and {p3}."},
        {"tributes": 4, "killed": ["2", "3", "4"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, and {p4}."},
        {"tributes": 5, "killed": ["2", "3", "4", "5"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, {p4} and {p5}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} as they tries to run."},
        {"tributes": 2, "killed": ["1", "2"], "string": "{p1} and {p2} threaten a double suicide. It fails and they die."},
        {"tributes": 4, "killed": ["1", "2", "3", "4"], "string": "{p1}, {p2}, {p3}, and {p4} form a suicide pact, killing themselves."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from hypothermia."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from hunger."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from thirst."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a hatchet."},
        {"tributes": 4, "killed": ["3", "4"], "string": "{p1} and {p2} fight {p3} and {p4}. {p1} and {p2} survive."},
        {"tributes": 4, "killed": ["1", "2"], "string": "{p1} and {p2} fight {p3} and {p4}. {p3} and {p4} survive."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies trying to escape the arena."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies of dysentery."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently detonates a land mine while trying to arm it."},
        {"tributes": 3, "killed": ["1"], "string": "{p1} attacks {p2}, but {p3} protects them, killing {p1}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} ambushes {p2} and kills them."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently steps on a landmine."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely slices {p2} with a sword."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} with a rope."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} for their supplies."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} shoots an arrow at {p2}, but misses and kills {p3} instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots a poisonous blow dart into {p2}'s neck, slowly killing them."},
        {"tributes": 6, "killed": ["4", "5", "6"], "string": "{p1}, {p2}, and {p3} successfully ambush and kill {p4}, {p5}, and {p6}."},
        {"tributes": 6, "killed": ["1", "2", "3"], "string": "{p1}, {p2}, and {p3} unsuccessfully ambush {p4}, {p5}, and {p6}, who kill them instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} with a tree branch."},
        {"tributes": 4, "killed": ["3"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They decides to kill {p3}."},
        {"tributes": 4, "killed": ["4"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They decides to kill {p4}."},
        {"tributes": 4, "killed": ["2"], "string": "{p1} forces {p2} to kill {p3} or {p4}. They refuses to kill, so {p1} kills them instead."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} poisons {p2}'s drink, but mistakes it for their own and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} poisons {p2}'s drink. They drinks it and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} in the back with a trident."},
        {"tributes": 2, "killed": ["1", "2"], "string": "{p1} attempts to climb a tree, but falls on {p2}, killing them both."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p1} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p2} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "2"], "string": "{p1}, {p2}, and {p3} get into a fight. {p3} triumphantly kills them both."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a sickle."},
        {"tributes": 6, "killed": ["6"], "string": "{p1}, {p2}, {p3}, {p4}, and {p5} track down and kill {p6}."},
        {"tributes": 5, "killed": ["5"], "string": "{p1}, {p2}, {p3}, and {p4} track down and kill {p5}."},
        {"tributes": 4, "killed": ["4"], "string": "{p1}, {p2}, and {p3} track down and kill {p4}."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} track down and kill {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} tracks down and kills {p2}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} repeatedly stabs {p2} to death with sais."}], 
    "feast": [
        {"tributes": 1, "killed": [], "string": "{p1} gathers as much food into a bag as they can before fleeing."},
        {"tributes": 1, "killed": [], "string": "{p1} sobs while gripping a photo of their friends and family."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} decide to work together to get more supplies."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} get into a fight over raw meat, but {p2} gives up and runs away."},
        {"tributes": 2, "killed": [], "string": "{p1} and {p2} get into a fight over raw meat, but {p1} gives up and runs away."},
        {"tributes": 3, "killed": [], "string": "{p1}, {p2}, and {p3} confront each other, but grab what they want slowly to avoid conflict."},
        {"tributes": 2, "killed": [], "string": "{p1} destroys {p2}'s memoirs out of spite."},
        {"tributes": 4, "killed": [], "string": "{p1}, {p2}, {p3}, and {p4} team up to grab food, supplies, weapons, and memoirs."},
        {"tributes": 2, "killed": [], "string": "{p1} steals {p2}'s memoirs."},
        {"tributes": 1, "killed": [], "string": "{p1} takes a staff leaning against the cornucopia."},
        {"tributes": 1, "killed": [], "string": "{p1} stuffs a bundle of dry clothing into a backpack before sprinting away."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} accidently steps on a landmine."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} catches {p2} off guard and kills them."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} work together to drown {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} after engaging in a fist fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots an arrow into {p2}'s head."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} bleeds out due to untreated injuries."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} cannot handle the circumstances and commits suicide."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head against a rock several times."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} snaps {p2}'s neck."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} decapitates {p2} with a sword."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} dies from an infection."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} spears {p2} in the abdomen."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets {p2} on fire with a molotov."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a pit and dies."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} while their back is turned."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2}, but puts them out of their misery."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely injures {p2} and leaves them to die."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} bashes {p2}'s head in with a mace."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} pushes {p2} off a cliff during a knife fight."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} throws a knife into {p2}'s chest."},
        {"tributes": 2, "killed": ["2"], "string": "{p1}'s trap kills {p2}."},
        {"tributes": 2, "killed": ["1"], "string": "{p1} is unable to convince {p2} to not kill them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} convinces {p2} to not kill them, only to kill {p2} instead."},
        {"tributes": 1, "killed": ["1"], "string": "{p1} falls into a frozen lake and drowns."},
        {"tributes": 3, "killed": ["3"], "string": "{p1}, {p2}, and {p3} start fighting, but {p2} runs away as {p1} kills {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with their own weapon."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} overpowers {p2}, killing them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} sets an explosive off, killing {p2}."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1} sets an explosive off, killing {p2}, and {p3}."},
        {"tributes": 4, "killed": ["2", "3", "4"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, and {p4}."},
        {"tributes": 5, "killed": ["2", "3", "4", "5"], "string": "{p1} sets an explosive off, killing {p2}, {p3}, {p4} and {p5}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} as they try to run."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} and {p2} threaten a double suicide. It fails and they die."},
        {"tributes": 4, "killed": ["1", "2", "3", "4"], "string": "{p1}, {p2}, {p3}, and {p4} form a suicide pact, killing themselves."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a hatchet."},
        {"tributes": 4, "killed": ["3", "4"], "string": "{p1} and {p2} fight {p3} and {p4}. {p1} and {p2} survive."},
        {"tributes": 4, "killed": ["1", "2"], "string": "{p1} and {p2} fight {p3} and {p4}. {p3} and {p4} survive."},
        {"tributes": 3, "killed": ["1"], "string": "{p1} attacks {p2}, but {p3} protects them, killing {p1}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} ambushes {p2} and kills them."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} severely slices {p2} with a sword."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} strangles {p2} with a rope."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} for their supplies."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} shoots an arrow at {p2}, but misses and kills {p3} instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} shoots a poisonous blow dart into {p2}'s neck, slowly killing them."},
        {"tributes": 6, "killed": ["4", "5", "6"], "string": "{p1}, {p2}, and {p3} successfully ambush and kill {p4}, {p5}, and {p6}."},
        {"tributes": 6, "killed": ["1", "2", "3"], "string": "{p1}, {p2}, and {p3} unsuccessfully ambush {p4}, {p5}, and {p6}, who kill them instead."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} with a tree branch."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} stabs {p2} in the back with a trident."},
        {"tributes": 3, "killed": ["2", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p1} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "3"], "string": "{p1}, {p2}, and {p3} get into a fight. {p2} triumphantly kills them both."},
        {"tributes": 3, "killed": ["1", "2"], "string": "{p1}, {p2}, and {p3} get into a fight. {p3} triumphantly kills them both."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} kills {p2} with a sickle."},
        {"tributes": 6, "killed": ["6"], "string": "{p1}, {p2}, {p3}, {p4}, and {p5} track down and kill {p6}."},
        {"tributes": 5, "killed": ["5"], "string": "{p1}, {p2}, {p3}, and {p4} track down and kill {p5}."},
        {"tributes": 4, "killed": ["4"], "string": "{p1}, {p2}, and {p3} track down and kill {p4}."},
        {"tributes": 3, "killed": ["3"], "string": "{p1} and {p2} track down and kill {p3}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} tracks down and kills {p2}."},
        {"tributes": 2, "killed": ["2"], "string": "{p1} repeatedly stabs {p2} to death with sais."}]}



