import discord
from discord.ext import commands
import aiohttp
import random

class BFME():
    """A cog for many BFME related commands"""
    def __init__(self, bot):
        self.bot = bot
        self.db = {
            "edain":[
                "Destroying a settlement while it's building doesn't give resources back.",
                "Destroying a settlement will return resource proportional to the amount of health left the building has. `Resources = (Building Cost / 2) * % of Health Left`",
                "Additional power points are gained depending on how many you currently have, the more power points the slower you gain them.",
                "Troll creeps will always hunt the closest nearby hero, with some micro you can easily drag him through some units to deal trample revenge damage.",
                "Internal resource buildings are well protected behind fortified walls but cost twice as much as external resource buildings.",
                "Swordsmen are strong against pikemen, Pikemen are strong against cavalry, Cavalry is strong against swordsmen and Archers are strong against all as long as they fight from afar.",
                "Heroes in Edain are separated in roles, try to understand them to make better use of them.",
                "Mass slayers excel at slaying massive amounts of weak enemies and usually are equipped with AoE attacks and/or abilities. They don't always deal a lot of damage but often deal it in an area.",
                "Some Mass Slayer abilities can also be used to output an extremely high amount of damage if the target is isolated, such as Legolas' Arrow Wind or Gandalf's Lightining Sword.",
                "Hero Killers excel at outputting high amounts of damage to single targets, the base is damage is often higher than average and their abilities help them stay close to the enemy.",
                "Units and Hero Interfers are all about disrupting the enemy's strategy and timing. They are equipped with abilities that do not inflict direct damage but rather inflict debuffs and statuses on the enemy.",
                "Timing is very important in Edain, prematurely using all your hero abilities and spellbook powers means the opponent can pull back and wait for the effects to fade, on the other hand, using them too late gives your opponent time to dish out damage meaning your powers might be less effective or you might miss on certain hero abilities",
                "Units and Hero Supporters focus on aiding your troops in battle and are equipped with a wide range of temporary and permanent buffs."
            ]
        }

        self.headers = {
            "Authorization" : "Bearer b836b21474d346f4a26798790096d8fb",
            "Content-Type" : "application/json",
            "Accept": "application/json"
        }

    @commands.command(name="helpme")
    async def tech_support(self, ctx):
        """A simple embed to list the most common errors

        {usage}"""

        embed = discord.Embed(title="Interactive Tutorial", colour=discord.Colour(0x277b0), description="Oh boy. Did something go wrong? Let's try to work it out together, okay?")
        bot_ico = "https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128"
        embed.set_footer(text="Generated by NecroBot", icon_url=bot_ico)

        embed.add_field(name="Error: Invalid Sound WOTR_MusicRohanMS", value="To fix the 2.02 V7 - Edain conflict you have to find your Rise of the Witch-King Installation Folder (where you installed 2.02) find the file named `!vanilla202music.big` and rename it to `vanilla202music.big` This will remove the priority for the file and therefore stop it from overwriting key Edain code. If the player has custom 2.02 music enabled then will need to rename `!new202music.big` to  `new202music.big` instead.")
        embed.add_field(name="Error: Upgrade_TREESTART", value="To fix simply disable the BFME2 1.09 patch (switch back 1.06), 1.09 is a fan made patch and is not compatible with ROTWK, causing it to crash. In addition, if you have Edain enabled, you need to update the mod through the launcher to avoid any pink textures")
        embed.add_field(name="Error: Pink Stuff", value="Update Edain through the launcher, if pink stuff still remains after that you'll need to re-install your game.")
        embed.add_field(name="Error: COMMAND_POINT_ELITE_ARCHER_10_UNIT", value="You have both Edain and 2.02 enabled, disable whichever you're not trying to launch and pray it didn't screw up with your mod files")
        embed.add_field(name="Error: ANGMAR_PERSONAL_HEAVY_COLLAR_BUILDTIME", value="Same as above")
        embed.add_field(name="Error: Game crashes when clicking skirmish", value="Disable edain and make sure that Goblins isn't selected in the vanilla skirmish menu. If it continues crashing, go to your romaing folder and move your Create A Hero files out.")
        embed.add_field(name="Error: Please insert CD-rom", value="Launch the game through the usual game shortcut, not through the Edain Launcher and make sure that your mini-images are properly mounted. [Read more...](https://www.gamereplays.org/riseofthewitchking/portals.php?show=news&news_id=966916)")
        embed.add_field(name="Error: Defeated after 3 minutes", value="The recommended approach is to re-install the game following [these](https://forums.revora.net/topic/105190-bfme1bfme2rotwk-games-download-installation-guide) instructions, you can also try editing the registry but this is not recommended.")
        embed.add_field(name="Error: Error mentions \"Error parsing ini block\"", value="Make sure you have other mods disabled or uninstalled and that all submods (which are not always uninstalled by uninstalling or disabling the main mod) are disabled or deleted. In addition, make sure that your BFME2 is set to 1.06 and that your ROTWK is set to whatever the mod requires, either 2.011or 2.02")

        await ctx.send(embed=embed)

    @commands.command()
    async def strategy(self, ctx, game):
        """Gives a random strategy tip for the version/game you desired.

        {usage}"""
        if game not in ["edain"]:
            await ctx.send(":negative_squared_cross_mark: | This version does not exist or is not yet supported.")
            return

        embed = discord.Embed(title="Strategy Tip", colour=discord.Colour(0x277b0), description=random.choice(self.db[game]))
        bot_ico = "https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128"
        embed.set_footer(text="Generated by NecroBot", icon_url=bot_ico)

        await ctx.send(embed=embed)

    @commands.command()
    async def install(self, ctx):
        """A simple embed incuding a bunch of helpful links

        {usage}"""
        embed = discord.Embed(title="Installation", colour=discord.Colour(0x277b0), description="Here are all the links you need to install the game and some of the most popular mods.")
        bot_ico = "https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128"
        embed.set_footer(text="Generated by NecroBot", icon_url=bot_ico)

        embed.add_field(name="Base Games", value="An installation guide for all three games can be found here: [Link](https://forums.revora.net/topic/105190-bfme1bfme2rotwk-games-download-installation-guide/?p=1028484)")
        embed.add_field(name="Patches", value="**BFME**\n-[All in one installer](http://server.cnc-online.net/downloads/patch/T3AOnlineBFME1_Patch1.06_AIO.exe)\n**BFME2**\n-1.06: [Link](http://www.gamereplays.org/battleformiddleearth21.08/portals.php?show=page&name=official-106-downloads) (this is required to play ROTWK)\n-1.09: [Link](https://www.gamereplays.org/battleformiddleearth2/portals.php?show=page&name=bfme2-patch-1.09) (This is a fan made patch and is not compatible with ROTWK, you must disable it when you want to play ROTWK)\n**ROTWK**\n-2.01: [Link](http://www.gamereplays.org/riseofthewitchking/portals.php?show=page&name=official-201-download) (Last official patch)\n-2.02: [Link](http://www.gamereplays.org/riseofthewitchking/portals.php?show=page&name=unofficial-patch-202-download-page) (A wildely popular unofficial balance patch required by some mods)")
        embed.add_field(name="Popular Mods", value="**[Edain](https://www.moddb.com/mods/edain-mod)**: Total conversion mod that brings back the BFME1 buildplots system in addition to numerous additions.\n**[AOTR](https://www.moddb.com/mods/the-horse-lords-a-total-modification-for-bfme)**: A mod with dozens of new heroes, units, spells and abilities aiming to create a diverse, engaging and balanced RTS faithful to Tolkien's mythos.\n**[BOTTA](https://www.moddb.com/mods/battles-of-the-third-age)**: A mod focused on realism, lore of the books and movies with improved balance focused more on a defensive playstyle.")
        await ctx.send(embed=embed)

    @commands.command()
    async def live(self, ctx, *, sentence):
        async with self.bot.session.post(f"https://api.dialogflow.com/v1/query", 
            headers=self.headers, 
            params={"v":"20170712"}, 
            json={"query": sentence, "sessionId": "botsession", "lang":"en"}
        ) as resp:
            r = await resp.json()

        await ctx.send(r["result"]["fulfillment"]["speech"])

def setup(bot):
    bot.add_cog(BFME(bot))