import discord
from discord.ext import commands

from rings.utils.utils import react_menu, has_perms, BotError

import feedparser
import asyncio
import datetime

class RSS(commands.Cog):
    """Cog for keeping up to date with a bunch of different stuff automatically."""

    def __init__(self, bot):
        self.bot = bot
        self.base_youtube = "https://www.youtube.com/feeds/videos.xml?channel_id={}"
        self.task = self.bot.loop.create_task(self.rss_task())

    def cog_unload(self):
        self.task.cancel()

    @commands.group(invoke_without_command = True, aliases=["yt"])
    @has_perms(3)
    async def youtube(self, ctx, youtuber_id : str = None, channel : discord.TextChannel = None):
        """Add/remove/edit a youtube stream. As long as you provide a channel, the stream will be set to that
        channel, if you don't provide a channel, the stream will be removed. To get the channel ID follow the steps:

        1. Go to the YouTube channel you want to track
        2. View the page’s source code
        3. Look for the following text: externalId
        4. Get the value right after externalID (it’ll look something like UCBcRF18a7Qf58cCRy5xuWwQ)

        It is also possible that the id of the channel is located at the end of the url, a simple check can confirm it, 
        if the endof the url (after the last /) is exactly or similar to the name of the channel then it isn't the id, if it 
        is more or less a random jumble of letters and numbers like the example in step 4 then it is most likely the id. 
        The bot will tell you if it couldn't find a channel to match the id given and will send you a sample video so you 
        can double check it is the correct channel.

        If you call the command without any arguments it will show you a list of youtube channels you are 
        subbed to and where the new videos are sent to.

        {usage}

        __Example__
        `{pre}youtube UCBcRF18a7Qf58cCRy5xuWwQ #streams` - subscribe to the youtube channel with this id and send all 
        new videos to the #streams
        `{pre}youtube` - list all yuotube channels you are subbed to and which discord channel they are being sent to.
        `{pre}youtube UCBcRF18a7Qf58cCRy5xuWwQ` - delete your subscription to this channel
        """
        if youtuber_id is None:
            feeds = await self.bot.db.get_yt_rss(ctx.guild.id)

            def embed_generator(page, entries):
                to_string = [f"[{result[2]}](https://www.youtube.com/channel/{result[2]}): {ctx.guild.get_channel(result[1]).mention} - `{result[4] if result[4] != '' else 'None'}`" for result in entries]
                embed = discord.Embed(title=f"Subscriptions ({page[0]}/{page[1]})", description = "\n".join(to_string))
                embed.set_footer(text="Generated by Necrobot", icon_url=self.bot.user.avatar_url_as(format="png", size=128))

                return embed

            return await react_menu(ctx, feeds, 15, embed_generator)

        async with self.bot.session.get(self.base_youtube.format(youtuber_id)) as resp:
            if resp.status != 200:
                raise BotError("This channel does not exist, double check the youtuber id.")
            
            feed = feedparser.parse(await resp.text())

        if channel is None:
            await self.bot.db.delete_rss_channel(ctx.guild.id, youtuber_id=youtuber_id)
            return await ctx.send(":white_check_mark: | You are no longer subscribed to this youtube channel")

        embed = discord.Embed(
            title=feed["feed"]["title"], 
            url=feed["feed"] ["link"]
        )
        
        embed.set_footer(text="Generated by Necrobot", icon_url=self.bot.user.avatar_url_as(format="png", size=128))
        
        await self.bot.db.upsert_yt_rss(ctx.guild.id, channel.id, youtuber_id)
        await ctx.send(f":white_check_mark: | New videos from this channel will now be posted in {channel.mention}. Here's the channel you have subbed to:", embed=embed)

    @youtube.command(name="filters")
    @has_perms(3)
    async def youtube_filters(self, ctx, youtuber_id : str, *, filters : str = ""):
        """This subcommand allows you to set a filter so that only videos which posses these keywords will be posted.
        The filter itself is very rudimentary but will work so that any video that has exactly these words (in
        any case) in that order in the title will be posted. You can clear filters by calling this command with just
        a youtuber id. Filters are limited to 200 characters

        {usage}

        __Examples__
        `{pre}youtube filters UCBcRF18a7Qf58cCRy5xuWwQ edain` - only post videos containing the word `edain`in their title
        `{pre}youtube filters UCBcRF18a7Qf58cCRy5xuWwQ - clear all filters for that channel, posting every video
        """
        await self.bot.db.update_yt_filter(ctx.guild.id, youtuber_id, filters.lower())
        if filters == "":
            await ctx.send(":white_check_mark: | Filters have been disabled for this channel")
        else:
            await ctx.send(f":white_check_mark: | Only videos with the words: **{filters}** will be posted for this yt channel")

    def convert(self, time):
        return datetime.datetime.strptime(time[:-3] + time[-2:], '%Y-%m-%dT%H:%M:%S%z')

    async def youtube_sub_task(self):
        feeds = await self.bot.db.query_executer("""
            SELECT youtuber_id, min(last_update), array_agg((channel_id, filter)::channel_filter_hybrid) 
            FROM necrobot.Youtube 
            GROUP BY youtuber_id
        """)
        
        time_limit = await self.bot.db.update_yt_rss()
        
        to_send = []
        
        for feed in feeds:
            async with self.bot.session.get(self.base_youtube.format(feed[0])) as resp:
                parsed_feed = feedparser.parse(await resp.text())["entries"]
                parsed_feed.reverse()

                to_send.append({
                    "channels": feed[2], 
                    "entries": [x for x in parsed_feed if time_limit > self.convert(x["published"]) > feed[1]]
                })

        for feed in to_send:
            for entry in feed["entries"]:
                embed = discord.Embed(title=entry["title"], description=entry["summary"][:2000], url=entry["link"])
                embed.set_author(name=entry["author_detail"]["name"], url=entry["author_detail"]["href"])
                embed.set_thumbnail(url=entry["media_thumbnail"][0]["url"])
                embed.set_footer(text="Generated by Necrobot", icon_url=self.bot.user.avatar_url_as(format="png", size=128))

                for channel_id, title_filter in feed["channels"]:
                    if title_filter in entry["title"].lower():
                        await self.bot.get_channel(channel_id).send(embed=embed)

    async def rss_task(self):
        await self.bot.wait_until_ready()
        while not self.bot.is_closed():
            try:
                await asyncio.sleep(900)
                await self.youtube_sub_task()
            except asyncio.CancelledError:
                return
            except Exception as e:
                self.bot.dispatch("error", e)

def setup(bot):
    bot.add_cog(RSS(bot))
