#!/usr/bin/python3.6
import discord
from discord.ext import commands
import time
from datetime import timedelta


class Support():
    """All the NecroBot support commands are here to help you enjoy your time with NecroBot """
    def __init__(self, bot):
        self.bot = bot
        self.feed = bot.get_channel(398894681901236236)

        
    @commands.command()
    async def about(self, ctx):
        """Creates a rich embed of the bot's details Also contains link for inviting and support server.

        {usage}"""

        bot_desc = "Hello! :wave: I'm NecroBot, a moderation bot with many commands for a wide variety of server and a high modularity which means you can enable/disable just about every part of me as you wish."
        embed = discord.Embed(title="__**NecroBot**__", colour=discord.Colour(0x277b0), description=bot_desc)
        embed.set_footer(text="Generated by NecroBot", icon_url="https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128")
        embed.add_field(name="Version", value=self.bot.version)
        embed.add_field(name="About", value="I'm currently in {} guilds and I can see {} members. I was created using Python and the d.py library. ".format(len(list(self.bot.guilds)), len(list(self.bot.users))))
        uptime = str(timedelta(seconds=time.time() - self.bot.uptime_start)).partition(".")[0].replace(":", "{}")
        embed.add_field(name="Uptime", value=uptime.format("hours, ", "minutes and ") + "seconds")
        embed.add_field(name="Links", value="[Invite bot to your server](https://discordapp.com/oauth2/authorize?client_id=317619283377258497&scope=bot&permissions=134737095) - [Get help with the bot](https://discord.gg/Ape8bZt)", inline=False)
        await ctx.channel.send(embed=embed)

    @commands.command()
    async def report(self, ctx, *, message):
        """Report a bug with the bot. Please be a specific as you can and check `{pre}faq` before.

        {usage}

        __Examples__
        `{pre}report profile while using profile the picture came out wrong, it was all distorted and stuff and my data on it was wrong.` - report 
        a bug for `profile`
        `{pre}report settings while using the sub-command mute it told me there was no such role when there is indeed` - report a bug for 
        `settings`"""

        msg = "{}".format(message)
        embed = discord.Embed(title=":bulb: A report has just came in :bulb:", description=msg, colour=discord.Colour(0x277b0))
        embed.set_footer(text="Generated by NecroBot", icon_url="https://cdn.discordapp.com/avatars/317619283377258497/a491c1fb5395e699148fcfed2ee755cf.jpg?size=128")
        embed.set_author(name=ctx.author.name, icon_url=ctx.author.avatar_url)
        embed.add_field(name="Helpful Info", value="User: {} \nServer: {} \nServer ID: {}".format(ctx.author.mention, ctx.guild.name, ctx.guild.id))
        await self.feed.send(embed=embed)


def setup(bot):
    bot.add_cog(Support(bot))